### ISSUE TITLE
using an SDXL model caused ram out of memory.

### ISSUE THREAD

**Issue by gilroff** [R3gm/SD_diffusers_interactive#1]
I only used text2img. The sdxl model is:
https://civitai.com/models/112013/acorn-is-spinning

**Comment by R3gm** [comment]
Hello @gilroff, at the moment, you can use SDXL models that are in the diffusers format, such as `stabilityai/stable-diffusion-xl-base-1.0`. But when possible, I will add compatibility for any SDXL model.

**Comment by gilroff** [comment]
Oh cool I'm waiting lol

**Comment by EPICbenis** [comment]
> Hello @gilroff, at the moment, you can use SDXL models that are in the diffusers format, such as `stabilityai/stable-diffusion-xl-base-1.0`. But when possible, I will add compatibility for any SDXL model.

is the sdxl models from civit ai supported yet?
