### ISSUE TITLE
using Lora fries the images

### ISSUE THREAD

**Issue by anahoss117** [R3gm/SD_diffusers_interactive#10]
i used a simple lora and it fried the images like if i used cfg scale to 50 or 70

using without lora gives normal output

![received_281769468144223](https://github.com/R3gm/SD_diffusers_interactive/assets/141332254/041476fc-5bd9-448e-a4d1-ae8b4af7b6e5)

**Comment by R3gm** [comment]
Hey there! Typically, we prefer employing lower values for CFG, but in some other SD setups, they've introduced something called Dynamic Thresholding, which comes in handy for High CFG Scale Fix. Right now, this isn't part of the interactive SD setup. High CFG can work with some models, but when a LoRA is used, a merge is performed with it, and the resulting model may not always function in the same way.
Even so, I will still be looking for other ways to load the LoRAs to make a better merge.
