### ISSUE TITLE
updating loras/models both

### ISSUE THREAD

**Issue by anahoss117** [R3gm/SD_diffusers_interactive#11]
im trying to download loras and model in bulk using my personal code. so.. basically im downloading models and loras and vaes using my own code.

but when i do it and click in step 3 to generate images...the models and loras doesn't show

can you provide the code in step 2 without the files downloading part(ill use my code for downloading vaes loras and models) in raw code 

thank you.

**Comment by R3gm** [comment]
Hello @anahoss117, 
To make the interface recognize new models, simply run cell 2 and then cell 3. 
Those first 90 lines of code in cell 2 are what allow you to download things and list all the valid models for the interface. Right now, I've limited big downloads to prevent any usage restrictions.
