### ISSUE TITLE
Text encoder token limit

### ISSUE THREAD

**Issue by Capostrophic** [R3gm/SD_diffusers_interactive#12]
So the text encoder has a token limit of 77, which is not that much. It would be really nice to have some sort of workaround like in A1111 UI.

**Comment by R3gm** [comment]
Hi @Capostrophic, 
Thank you for your interest. I have been seeing that it is a highly requested feature, and it is definitely something we will consider in future iterations of the project. I will be looking into how it can be implemented to enhance the overall functionality.
