### ISSUE TITLE
Red and Green dots in output when using SDXL

### ISSUE THREAD

**Issue by DuckytheQuack** [R3gm/SD_diffusers_interactive#14]
Hello! I really love the notebook and it works great most of the time, and i am so thankful that you created it. I love that it's able to use SDXL smoothly without any hiccups but i've noticed some strange artifacts that appear on the final image. I read that it has something to do with the VAE but no matter which SDXL model i use or which VAE i pair it with, it still looks the same. Here's an image showing what the issue is:
![Skdärmklipp](https://github.com/R3gm/SD_diffusers_interactive/assets/98208745/2824cbce-9536-468d-812a-cd09a2777995)

The artifacts that are left behind are the red and green dots that are in the image. They're very small but they are so many that it's hard to overlook.
The particular image the screesnhot is of was created with the RealVisXL model that comes default as a diffuser in the notebook.
The models i have tried have all worked well in comfyUI without any artifacts but here, no matter the different settings i've toggled on and off, the artifacts have persisted and can not be removed.

Is it possible to fix this somehow?
Thank you!

**Comment by R3gm** [comment]
Hello @DuckytheQuack, the latest update solved the issue, but if it continues, let me know
