### ISSUE TITLE
Feature suggestion - image metadata in "UI"

### ISSUE THREAD

**Issue by Vsevolod-Shustov** [R3gm/SD_diffusers_interactive#15]
Would it be possible to add image names and generation metadata like prompt to images showed via widgets so they can be saved with metadata from right click menu? Currently, these images have generic "download.png" name and no metadata.

**Comment by R3gm** [comment]
Hello @Vsevolod-Shustov, for now, images with metadata are saved in the 'images' folder in Colab; they can also be downloaded using the right-click menu.
I might consider adding that feature you described, but at the moment, it's not my main focus. Thanks!
