### ISSUE TITLE
Installed model, but in dropdown menu, no model.

### ISSUE THREAD

**Issue by ReEnMikki** [R3gm/SD_diffusers_interactive#2]
title

**Comment by ReEnMikki** [comment]
Ok, for some reasons ckpt model files aren't allowed. Bruh moment

**Comment by R3gm** [comment]
Hey there, I made an attempt to address the problem you mentioned by adding CKPT models. However, it's worth noting that there could still be some challenges when it comes to loading these models.

**Comment by ReEnMikki** [comment]
> Hey there, I made an attempt to address the problem you mentioned by adding CKPT models. However, it's worth noting that there could still be some challenges when it comes to loading these models.

Thanks, btw I hope you'll look into the Lora problem next which I issued
