### ISSUE TITLE
Model selection dropdown box

### ISSUE THREAD

**Issue by hiroyuki-fx** [R3gm/SD_diffusers_interactive#3]
The previous versions of the notebook were working fine, but since the version that adds support for multiple LORAs the names of the models in the dropdown selection box started appearing like

('modelname','models/modelname.safetensors')

Trying to run the image generating cell selecting a model in this state results in an error. Previous versions of the notebook work fine.

After some tinkering i managed to fix it by deleting this line from the "Download model" cell.

model_list.append(process_string(load_diffusers_format_model))

**Comment by ReEnMikki** [comment]
the dropdown menu of model won't even appear any option for me, despite that I downloaded the model

**Comment by R3gm** [comment]
Hi @hiroyuki-fx,

The modification has resolved the issue.
