### ISSUE TITLE
images save

### ISSUE THREAD

**Issue by atmospxl** [R3gm/SD_diffusers_interactive#6]
when i generate 2 images or more, only one image save to images folder and when i try generate 9 or more, no images save to images folder and got error like this :

OSError                                   Traceback (most recent call last)
[<ipython-input-4-94cc94741585>](https://localhost:8080/#) in generate_img(i)
    722             image_name = f'{slugify}-seed{seed}-{idx} random_number{str(random_number)}.png'
    723             image_path = directory_images + '/' + image_name
--> 724         image.save(image_path)
    725         image_list.append(image_path)
    726 

[/usr/local/lib/python3.10/dist-packages/PIL/Image.py](https://localhost:8080/#) in save(self, fp, format, **params)
   2426                 fp = builtins.open(filename, "r+b")
   2427             else:
-> 2428                 fp = builtins.open(filename, "w+b")
   2429 
   2430         try:

OSError: [Errno 36] File name too long:

**Comment by R3gm** [comment]
Hi @atmospxl , I've successfully resolved the issue
