### ISSUE TITLE
Can hire fixes be added?

### ISSUE THREAD

**Issue by Lucysck** [R3gm/SD_diffusers_interactive#8]
And the error reported in the Upscale and face restoration part
![image](https://github.com/R3gm/SD_diffusers_interactive/assets/125596007/077f2401-37ef-4fd6-86de-ea72e5de4f71)
![image](https://github.com/R3gm/SD_diffusers_interactive/assets/125596007/24f64b89-64b2-40c6-9de1-d949367abb50)

**Comment by R3gm** [comment]
Hello @Lucysck, I couldn't replicate the issue, but I've included an extra feature: an alternative upscaler. So, in case one doesn't work, you can use the other one.

**Comment by Lucysck** [comment]
Thanks to you, it works fine now.
In addition, will it be possible to support hire fixes and more extensions in the future?
Can models in additional folders inside the model folder be read?

**Comment by R3gm** [comment]
Hi
Thanks for the feedback! I'm glad to hear that it's working fine now.
Yes, I'm working on a better implementation of hi-res fix for the future, the alternative upscaler is very similar to the one commonly used hi-res fix.  I don't have any plans to add more extensions right now, but I'll keep that in mind for the future
Only models in the models folder can be read right now.
Thanks 🤗
